### ISSUE TITLE
Switch from C++ SPQR script to generating SPQR trees in Python

### ISSUE THREAD

**Issue by fedarko** [marbl/MetagenomeScope#154]
One of the big pain points about installing MetagenomeScope on various systems has been building the C++ code for SPQR trees accordingly. Currently this is an "optional" feature which requires a bunch of [installing stuff](https://github.com/marbl/MetagenomeScope/wiki/Installation-Instructions#optional-installing-metagenomescope-with-spqr-tree-support)... it's not that bad, but it does significantly hamper usability of the tool.

Turns out that [the SageMath package recently added SPQR tree support](http://doc.sagemath.org/html/en/reference/graphs/sage/graphs/connectivity.html). This would theoretically let us make MetagenomeScope a purely-python (at least from our side of things) package, which would make it a lot easier to install it on different platforms. It'd also reduce the amount of [auxiliary files created](https://github.com/marbl/MetagenomeScope/wiki/Preprocessing-Script-Options#script-output) while running MetagenomeScope with the `-spqr` option (no need to use these files to communicate between the python and C++ code).

**Sticking points of doing this:**
- as far as I can tell, Sage only has experimental support for Python 3 as of writing. However, I expect this will change soon since Python 2 will stop being supported at the end of the year :), so that's not that big of a deal.
  - Also, building the Baobab (2015.05) release of OGDF fails in Python 3 environments also... so there are going to be challenges whichever path we choose.
- The SPQR script doesn't just construct a single SPQR tree—it computes a Block-Cut Tree from a graph, and then computes an SPQR tree for every "B" node (i.e. each biconnected component of the graph) where possible. (This is done in the `main()` function of spqr.cpp.) We'd need to rewrite this functionality in Python using Sage. This will likely take at minimum a few days.

**Steps to get this working:**
- [x] Verify that Sage is installable by conda into a python 3 environment, and that it has SPQR tree support
  - I checked, and things seem to work ok. You need to `import sage.all` first before you can import other stuff.
  - See [here](http://doc.sagemath.org/html/en/reference/graphs/sage/graphs/connectivity.html) for examples of creating SPQR trees from Graphs in Sage.
  - Looks like the [`TriconnectivitySPQR.get_triconnected_components()`](http://doc.sagemath.org/html/en/reference/graphs/sage/graphs/connectivity.html#sage.graphs.connectivity.TriconnectivitySPQR.get_triconnected_components) method is what we'll want.
- [ ] Add a method that computes a graph stored in memory in MetagenomeScope's preprocessing script to a Sage Graph (`sage.graphs.graph.Graph`).
  - An alternate approach would just be building up a NetworkX or Sage graph object when parsing assembly graphs, instead of just using the weird dict structure we currently have. Probably easiest to just work with what we have, though: this alternate approach would require *a ton* of restructuring.
- [ ] Add unit-tests for the above method
- [ ] Add a method that converts a Sage Graph to a BC Tree, converts each B-node to a SPQR tree where possible, and constructs graph objects representing this tree in MetagenomeScope. This would replace the current code we have that reads in the `component_*.info` and `spqr*.gml` files.
- [ ] Add unit-tests for above method (it'll likely be composed of multiple sub-methods).
- [ ] Once everything is integrated, update installation instructions, acknowledgements, etc. accordingly in the documentation.

**Comment by fedarko** [comment]
This is going to require a decent amount of work, but I *think* it'll be worth it in the end.

**Comment by N-Coder** [comment]
FYI: I'm working on a fully-featured python API for the OGDF. You can find the bindings [here](https://github.com/N-Coder/ogdf-python), which should make it pretty easy to translate your C++ code to pure python. The bindings can use a locally built version of the OGDF as dynamic library, while I also provide a [python package with a prebuilt OGDF](https://github.com/N-Coder/ogdf-wheel) for convenience. Combining both, you could get rid of both the C++ part of your library and the need to compile (any) C++ code for installing. Unfortunately, I still have some issues with packaging the OGDF for Windows, which is why the prebuilt package is currently only available on Linux. Using local builds of the OGDF still works perfectly fine on any system.

**Comment by fedarko** [comment]
That's extremely cool—thank you for the heads-up! I've been moving this project away from using SPQR trees (for reasons besides implementation difficulties—currently I feel that SPQR trees aren't the best fit for our needs), but I'll probably need to work with SPQR trees for other purposes in the future. When that day comes, I look forward to using your API :)
